### PR TITLE
Binary tweaks

### PR DESCRIPTION
**Pull request by mikemcquaid**
- use https for binaries
- use new download location. Well, I say "new" but this also means that the bottles from before the base64 encoding was used.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
See also: https://github.com/boxen/our-boxen/pull/729

**Comment by blackjid** [comment]
hi @mikemcquaid , I've been using the sync script I don't quite understand why some homebrew packages are not being snapshoted and uploaded to s3. It says `Please set the HOMEBREW_BUILD_BOTTLE env var and reinstall`. In this issue you are saying that we must set that env variable ourselfs if we want to.

Can you please tell me what are the downsides of settings this variable??? What is the value I should use? also, why there are some packages that does indeed are synced???

thanks!

**Comment by mikemcquaid** [comment]
Hopefully this explains: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Bottles.md#bottle-creation

**Comment by blackjid** [comment]
Thanks, I understand now what are bottles and how they work outside the boxen. 

Why this PR changed the default behavior? That's why I have some brew that are being synced? I have this mac installation since before you made this change and I updated this module on my boxen.

Should I just add the HOMEBREW_BUILD_BOTTLE env to my boxen if I want the binaries to be synced?

Sorry for all the questions.. :P

**Comment by mikemcquaid** [comment]
Basically bottles that aren't built with that flag won't work if built on a newer Mac and installed on an older one. You don't want to add `HOMEBREW_BUILD_BOTTLE` as to your environment as that will prevent anything from using downloaded bottles that e.g. Homebrew or Boxen already provides. The best thing to do is use `brew reinstall --build-bottle` for any packages you wish to `./script/sync`. Good luck!

**Comment by blackjid** [comment]
thanks!!, if there is any formula like [postgis formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/postgis.rb#L7-L12) that defines the `pour_bottle?` method to return `false`, I will not be able to sync that package, right?

**Comment by blackjid** [comment]
I tried and it was synced.... :P

**Comment by mikemcquaid** [comment]
@blackjid You can sync it but it may not be actually installed.

**Pull request merged**
