### PR TITLE
Move boxen-* commands into the tap's cmd directory.

### PR DESCRIPTION
**Pull request by mikemcquaid**
If you use Boxen with Homebrew in `/usr/local` you currently get a nasty `brew doctor` message like:

```
Warning: You have uncommitted modifications to Homebrew
If this a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
    cd /usr/local/Library && git stash && git clean -d -f
```

Due to the following (from `git status`):

```
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Library/Homebrew/boxen-bottle-hooks.rb
	Library/Homebrew/cmd/boxen-install.rb
	Library/Homebrew/cmd/boxen-latest.rb
	Library/Homebrew/cmd/boxen-upgrade.rb
```

It'd be nice instead to install these wrappers into Boxen's tap where Homebrew will add them to its `PATH` instead.

CC @dgoodlad

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Another (probably better) approach here is to put these in the `cmd` directory of a real Boxen tap.

**Comment by mikemcquaid** [comment]
@dgoodlad Any thoughts on this (or similar)?

**Comment by dgoodlad** [comment]
@mikemcquaid I really like the option of pushing those into the tap's `cmd` directory

**Comment by mikemcquaid** [comment]
@dgoodlad Cool, will take a look at fixing that up in this PR.

**Comment by mikemcquaid** [comment]
Moved to putting these into the tap's `cmd` directory. The code is actually a lot cleaner this way everywhere so I think it's a good fix.

**Comment by mikemcquaid** [comment]
@dgoodlad @rafaelfranca Any news on this? Would really like to get this merged in.

**Comment by tarebyte** [comment]
@mikemcquaid I pulled down your branch and ran it on my personal Boxen.

I received this error while running `boxen` with your branch

```
Error: Could not apply complete catalog: Found 1 dependency cycle:
(File[/opt/boxen/env.d/10_homebrew.sh] => Boxen::Env_script[homebrew] => Class[Homebrew] => Homebrew::Formula[gcc48] => File[/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews] => File[/opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

Did you run into this error at any point? Not entirely sure what it means. I'll do some research

**Comment by mikemcquaid** [comment]
I can't see those two being related given I've not touched any related files. Weird.

**Comment by dgoodlad** [comment]
:+1:

**Pull request merged**
