### PR TITLE
Deprecate `BoxenBottles` and Homebrew hooks

### LINKED ISSUE #105: Deprecate Homebrew::Hooks
It would be nice to be able to deprecate Homebrew::Hooks::Bottles and have Boxen use Homebrew's native bottles at this stage.

Thoughts?

### PR DESCRIPTION
**Pull request by jacobbednarz**
Vendored S3 Homebrew binaries were from a time when Homebrew was less
reliable and shouldn't be a required practice anymore. This cleans up
the shims and `BoxenBottles` related code.

Closes #105

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> when Homebrew was less reliable

allegedly 😉 

Otherwise: 👍, great work, thanks!

**Comment by MikeMcQuaid** [comment]
@jacobbednarz 🚢?

**Comment by jacobbednarz** [comment]
This has kept falling behind other priorities (like Homebrew `etc` install restrictions and getting Boxen to run on 10.13) however I'll try and get this tested in the coming weeks.

**Comment by MikeMcQuaid** [comment]
@jacobbednarz Great, no worries.

**Pull request merged**
